
  lavalink:
    image: fredboat/lavalink:dev
    container_name: discord-js-lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - discord-js-net
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro

  mongodb:
    image: mongo:latest
    container_name: discord-js-mongodb
    restart: unless-stopped
    networks:
      - discord-js-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=supersecretpassword
    volumes:
      - ./data:/data/db:rw

networks:
  discord-js-net:
    name: discord-js-net
